### ISSUE TITLE
Click Event of Control inside THorzScrollView not fireing

### ISSUE THREAD

**Issue by shariful2011** [yangyxd/FMXUI#4] opened 2018-03-07 11:44 UTC
I am trying to make a slide horizontal slide menu using THorzScrollView but unable to execute Click event inside any control of THorzScrollView. I set HitTest := True to THorzScrollView Child Control but no event is fireing. Can you please guid how to achive it?

**Comment by KngStr** [comment] 2019-06-25 11:07
Well. Do you still here, and have this problem? 
If not, I would like to close this issue. Because I can't reproduce. 
Thanks.

**Closed by KngStr** 2019-06-25 11:07 UTC
